name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure your default branch is main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_TOKEN }}  # Your newly generated PAT secret
          publish_dir: ./dist                      # Change this if your output folder is different
          publish_branch: gh-pages
